apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: your-namespace
type: Opaque
data:
  DB_USER: bXlfdXNlcg==   # Base64 encoded value of 'my_user'
  DB_PASS: bXlfcGFzc3dvcmQ= # Base64 encoded value of 'my_password'
